### ISSUE TITLE
Steam launch command error

### ISSUE THREAD

**Issue by 0Redhell** [Lyall/Octopath2Fix#1]
I'm getting an error on Windows 11 for the steam launcher command, I attached a picture. No idea how to solve it, or is it Windows 11 related issue or something.

https://i.imgur.com/vXbOWyJ.png

**Comment by Lyall** [comment]
Ah you don't need to use that launch command on Windows. It's just there for Linux/Steam Deck users. You can safely delete that launch command and it should load the fix just fine provided you have extracted it to the correct place.

**Comment by 0Redhell** [comment]
oh, didn't know that. I tried it without the command and working just fine thanks alot <3
