### ISSUE TITLE
Gamepass Version

### ISSUE THREAD

**Issue by Dark-talon** [Lyall/Octopath2Fix#10]
Can you please make this compatible with the Gamepass version? Here is the log when I ran it. (Also it didnt uncap the fps or fix the aspect ratio)

[Octopath2Fix.log](https://github.com/user-attachments/files/15685852/Octopath2Fix.log)

**Comment by Dark-talon** [comment]
A follow up to this, I was able to get it to partially work, by creating the config folder path it was expecting. I created the Win64 folder under binaries and put the octopath2fix.ini in it, while leaving the rest of the mod files next to the exe, which is now found under WinGDK. Ultrawide seems to work but other aspects of the mod are broken. Here is the new log.
[Octopath2Fix.log](https://github.com/user-attachments/files/15685948/Octopath2Fix.log)

**Comment by prestonsmartuk** [comment]
Looking for a Gamepass fix too

**Comment by Lyall** [comment]
I'm currently working on a [rewrite](https://github.com/Lyall/Octopath2Fix/tree/rewrite) that should fix this and be compatible with the Gamepass build. Unfortunately it looks like a few other things are broken from either the last update or this latest one so bear with me while I try and get it sorted.

**Comment by Lyall** [comment]
I have rewritten the project and updated every fix to work with the latest versions of the game available on Steam/Xbox Gamepass. If you run in to any problems, feel free to open another issue.
