### ISSUE TITLE
Steamdeck view compressed

### ISSUE THREAD

**Issue by jiGGij** [Lyall/Octopath2Fix#3]
Added the files to the install folder in the steamdeck, added the command line, and now the game launches in an extremely small, pillarboxed view 
![IMG_0601](https://user-images.githubusercontent.com/128978691/227807540-de9b4bbb-3dfb-49b2-9561-50600e8d3029.jpg)

**Comment by Lyall** [comment]
Are you able to navigate to the video settings to change resolution to something else then back again? Or do the pillarboxes make that impossible?

**Comment by jiGGij** [comment]
No, I'm dumb and this is the result of launching in desktop mode.  I deleted the mod, tried the game again and got the same result.  I originally tried launching in gaming mode and could not get the game to launch with the mod added. So I figured I'd attempt launching in desktop mode, which resulted in this pillarboxed view (modded or not).  I reinstalled the mod and the command launch, launched in game mode and its now working as intended.  Thank you!
