### ISSUE TITLE
The mask when entering battle is not 21:9 after the game update in Aug 9

### ISSUE THREAD

**Issue by whisssky** [Lyall/Octopath2Fix#6]
![20230812113302_1](https://github.com/Lyall/Octopath2Fix/assets/12016481/69e922df-dcd4-4819-a829-3b382f97b3da)

Octopath2 has a small update in steam recently, and when updated, the mask when entering battle is not 21:9 (Just in this place has issue, others places still work fine).
Could you help to solve this issue?  Thanks a lot~~~
I am a big fan of 21:9 and Octopath2

**Comment by whisssky** [comment]
I download an old version of Octopath2 by steam console, and using old Octopath_Traveler2-Win64-Shipping.exe to replace the new exe, and the issue is solved

**Comment by bad1dea** [comment]
nm i managed to update the AOB's for latest release.

**Comment by bad1dea** [comment]
[Octopath2Fix.zip](https://github.com/Lyall/Octopath2Fix/files/12788078/Octopath2Fix.zip)

I updated the ASI for the latest version on steam, if you want to test it @whisssky - fixed FadeBG / BattleWipe / FPS which was failing due to changes to code.

**Comment by whisssky** [comment]
> [Octopath2Fix.zip](https://github.com/Lyall/Octopath2Fix/files/12788078/Octopath2Fix.zip)
> 
> I updated the ASI for the latest version on steam, if you want to test it @whisssky - fixed FadeBG / BattleWipe / FPS which was failing due to changes to code.

@bad1dea  Thanks for you help!  I update my game to the latest version, then copy the .asi file to the game folder. Unfortunately, there is a fatal error dialog when I launch the game. Here is the Octopath2Fix.log
[Octopath2Fix.log](https://github.com/Lyall/Octopath2Fix/files/12804600/Octopath2Fix.log)

**Comment by bad1dea** [comment]
interesting, can you confirm the build id from your octopath? :) details tab 

I may have to edit up the AOB to allow for wildcards.

**Comment by whisssky** [comment]
@bad1dea   The build id is 10440977

**Comment by Lyall** [comment]
Fixed in [v0.9.0](https://github.com/Lyall/Octopath2Fix/releases).

**Comment by whisssky** [comment]
Thanks!
